//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A01
    {
        public string RowID { get; set; }
        public string PersonID { get; set; }
        public int DispOrder { get; set; }
        public string PClassID { get; set; }
        public string A01C01 { get; set; }
        public string E0389 { get; set; }
        public string A0101 { get; set; }
        public string B0001 { get; set; }
        public string B0002 { get; set; }
        public string B000201 { get; set; }
        public string B000202 { get; set; }
        public string B000203 { get; set; }
        public string B000204 { get; set; }
        public string B000205 { get; set; }
        public string B0003 { get; set; }
        public string E0386 { get; set; }
        public string E0387 { get; set; }
        public Nullable<System.DateTime> E0359 { get; set; }
        public string E0394 { get; set; }
        public Nullable<decimal> E0368 { get; set; }
        public byte[] PersonPhoto { get; set; }
        public string A0177 { get; set; }
        public Nullable<System.DateTime> A0111 { get; set; }
        public string A0107 { get; set; }
        public Nullable<int> C0101 { get; set; }
        public string A0108 { get; set; }
        public string A0121 { get; set; }
        public string A0114 { get; set; }
        public string A0115 { get; set; }
        public string A0109 { get; set; }
        public string A0112 { get; set; }
        public Nullable<System.DateTime> A0116 { get; set; }
        public Nullable<System.DateTime> A0117 { get; set; }
        public string A0110 { get; set; }
        public string A0127 { get; set; }
        public string A0128 { get; set; }
        public string C01SS { get; set; }
        public string C01RV { get; set; }
        public string C0102 { get; set; }
        public string A0141 { get; set; }
        public string A0142 { get; set; }
        public string A0143 { get; set; }
        public string A0145 { get; set; }
        public string A0146 { get; set; }
        public string A0118 { get; set; }
        public Nullable<System.DateTime> A0119 { get; set; }
        public Nullable<long> OrgDispOrder { get; set; }
        public string B00022 { get; set; }
        public string B00023 { get; set; }
        public string A0120 { get; set; }
        public string A0122 { get; set; }
        public string C0104 { get; set; }
        public Nullable<long> A0178 { get; set; }
        public Nullable<System.DateTime> A0179 { get; set; }
        public string A0180 { get; set; }
        public string A0181 { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string in_type { get; set; }
        public string UnitID { get; set; }
        public string big_iris_data { get; set; }
        public Nullable<System.DateTime> retire_time { get; set; }
        public string retire_handle_user { get; set; }
        public string in_team { get; set; }
        public string scan_contract { get; set; }
        public string SSDWLB { get; set; }
        public string SSDWZW { get; set; }
        public string GZGZHDFS { get; set; }
        public string GZGZHDBZ { get; set; }
        public string SSBZ { get; set; }
        public string SFBZFZR { get; set; }
        public string SFQDJYYGHT { get; set; }
        public string lzyy { get; set; }
        public Nullable<int> update_id { get; set; }
        public int if_remove { get; set; }
        public string NMGZHSSYH { get; set; }
        public string if_uparchive { get; set; }
        public string if_upphoto { get; set; }
        public string if_upscanfile { get; set; }
    }
}
