//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A02
    {
        public string RowID { get; set; }
        public string PersonID { get; set; }
        public int DispOrder { get; set; }
        public byte IsLastRow { get; set; }
        public Nullable<System.DateTime> A0201 { get; set; }
        public string A0202 { get; set; }
        public string A0203 { get; set; }
        public string A0204 { get; set; }
        public string fill_check { get; set; }
        public string fill_reason { get; set; }
        public Nullable<int> fill_user_id { get; set; }
        public string xNum { get; set; }
        public string yNum { get; set; }
        public string if_upattend { get; set; }
    }
}
