//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A19
    {
        public string RowID { get; set; }
        public string PersonID { get; set; }
        public int DispOrder { get; set; }
        public byte IsLastRow { get; set; }
        public string A1915 { get; set; }
        public Nullable<System.DateTime> A1905 { get; set; }
        public Nullable<System.DateTime> A1910 { get; set; }
        public string A1927 { get; set; }
        public string A1920 { get; set; }
        public string A1928 { get; set; }
        public string A1929 { get; set; }
        public string A1930 { get; set; }
        public string A1925 { get; set; }
        public string A1926 { get; set; }
    }
}
