//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACHJOB
    {
        public string RowID { get; set; }
        public string PersonID { get; set; }
        public int DispOrder { get; set; }
        public byte IsLastRow { get; set; }
        public string JobB0001 { get; set; }
        public string JobB0002 { get; set; }
        public string JobB0003 { get; set; }
        public string JobAttachName { get; set; }
        public string JobClass { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public string JobReason { get; set; }
        public string JobIsActivity { get; set; }
    }
}
