//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_UserLogon
    {
        public string RowID { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> FirstLogonDate { get; set; }
        public Nullable<System.DateTime> LastLogonDate { get; set; }
        public Nullable<System.DateTime> LastModifyPasswordDate { get; set; }
        public Nullable<int> LogonCount { get; set; }
        public Nullable<int> ErrorPasswordCount { get; set; }
        public string Question { get; set; }
        public string QuestionAnswer { get; set; }
    }
}
