//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_UserWeixin
    {
        public string RowID { get; set; }
        public string UserID { get; set; }
        public string WxOpenID { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
