//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Define_DataScopeItem
    {
        public string RowID { get; set; }
        public string ScopeID { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public int ItemType { get; set; }
        public string ItemConfig { get; set; }
        public int IsActivity { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string ConditionSql { get; set; }
        public Nullable<int> DetailShowTree { get; set; }
        public Nullable<int> DetailState { get; set; }
        public Nullable<int> DetailLoadOneTime { get; set; }
        public string DetailSql { get; set; }
    }
}
