//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_User
    {
        public string RowID { get; set; }
        public string GroupID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string PersonName { get; set; }
        public string Password { get; set; }
        public int IsActivity { get; set; }
        public int IsDevelop { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string PersonID { get; set; }
        public string UnitID { get; set; }
        public string DeptID { get; set; }
        public string PositionID { get; set; }
        public string Descript { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string QQ { get; set; }
        public int IsPersonSelf { get; set; }
    }
}
