//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class B01
    {
        public string RowID { get; set; }
        public string UnitID { get; set; }
        public int DispOrder { get; set; }
        public string KeyParent { get; set; }
        public int KeyChild { get; set; }
        public string UnitType { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> UnitStartDate { get; set; }
        public Nullable<System.DateTime> UnitEndDate { get; set; }
        public string B0107 { get; set; }
        public string B0108 { get; set; }
        public string B0120 { get; set; }
        public string D010H { get; set; }
        public string B0175 { get; set; }
        public Nullable<System.DateTime> B0109 { get; set; }
        public Nullable<System.DateTime> B0110 { get; set; }
        public string B0111 { get; set; }
        public string B0112 { get; set; }
        public string B0180 { get; set; }
        public string B0130 { get; set; }
        public string B0113 { get; set; }
        public Nullable<decimal> B0114 { get; set; }
        public Nullable<decimal> B0115 { get; set; }
        public Nullable<decimal> B0116 { get; set; }
        public string B0117 { get; set; }
        public string B0118 { get; set; }
        public string B0181 { get; set; }
        public Nullable<decimal> B01WAGE { get; set; }
        public string UnitManage { get; set; }
        public string B0182 { get; set; }
        public Nullable<System.DateTime> B0183 { get; set; }
        public string B0184 { get; set; }
        public Nullable<System.DateTime> B0185 { get; set; }
        public string B0186 { get; set; }
        public string project_status { get; set; }
        public Nullable<System.DateTime> refresh_time { get; set; }
        public string Xmbh { get; set; }
        public string Xxly { get; set; }
        public string FBR { get; set; }
        public string CBR { get; set; }
        public string GCLXPZWH { get; set; }
        public string ZJLY { get; set; }
        public string HTBH { get; set; }
        public string ZBBH { get; set; }
        public string XMJHZGQ { get; set; }
        public string QYHTJ { get; set; }
        public string CBRXMJLXM { get; set; }
        public string CBRXMJLZC { get; set; }
        public string CBRXMJLSFZH { get; set; }
        public string CBRXMJLZCJZSZGZSBH { get; set; }
        public string CBRXMJLZCJZSZSZCBH { get; set; }
        public string CBRXMJLZCJZSZYYZH { get; set; }
        public Nullable<System.DateTime> XMHTQDRQ { get; set; }
        public string FBRZZ { get; set; }
        public string FBRDH { get; set; }
        public string FBRFDDBR { get; set; }
        public string FBRCZ { get; set; }
        public string FBRKHYH { get; set; }
        public string FBRYHZH { get; set; }
        public string FBRYZBM { get; set; }
        public string FBRDZ { get; set; }
        public string CBRZZ { get; set; }
        public string CBRDH { get; set; }
        public string CBRFDDBR { get; set; }
        public string CBRCZ { get; set; }
        public string CBRKHYH { get; set; }
        public string CBRYHZH { get; set; }
        public string CBRYZBM { get; set; }
        public string CBRDZ { get; set; }
        public string SSXZZGBM { get; set; }
        public string BASBLX { get; set; }
        public string BASBBH { get; set; }
        public string SSWG { get; set; }
        public string XMCJR { get; set; }
        public string FXMID { get; set; }
        public string SSDWYHID { get; set; }
        public string SFCJGSBX { get; set; }
        public string XMBZJYCJE { get; set; }
        public string LZZGY { get; set; }
        public string FXRQ { get; set; }
        public string ZZJGDM { get; set; }
        public string GSDJZZZL { get; set; }
        public string GSDJZZHM { get; set; }
        public string SHXYDM { get; set; }
        public string LSJG { get; set; }
        public string in_compay { get; set; }
        public string GCLB { get; set; }
        public string FBDW { get; set; }
        public string JSDWLXR { get; set; }
        public string JSDWLXRDH { get; set; }
        public string SGDWLXR { get; set; }
        public string SGDWLXRDH { get; set; }
        public string LZZGYYI { get; set; }
        public string LZZGYYILXFS { get; set; }
        public string LZZGYER { get; set; }
        public string LZZGYERLXFS { get; set; }
        public string LZZGYSAN { get; set; }
        public string LZZGYSANLXFS { get; set; }
        public string GZFFZHSSYH { get; set; }
        public string xMax { get; set; }
        public string xMin { get; set; }
        public string yMax { get; set; }
        public string yMin { get; set; }
        public string upLoadName { get; set; }
        public string upLoadId { get; set; }
        public string if_upload { get; set; }
    }
}
