//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_CashDetail
    {
        public int cd_id { get; set; }
        public int ip_id { get; set; }
        public System.DateTime cash_start_date { get; set; }
        public System.DateTime cash_end_date { get; set; }
        public decimal cash_money { get; set; }
    }
}
