//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_DWState
    {
        public string sInstanceID { get; set; }
        public string sClassID { get; set; }
        public string sTBID { get; set; }
        public long sDWID { get; set; }
        public string sFlag { get; set; }
        public int sYear { get; set; }
        public int sTypeID { get; set; }
        public Nullable<int> sTypeCycleID { get; set; }
        public Nullable<int> CheckState { get; set; }
        public Nullable<System.DateTime> SendDataState { get; set; }
        public string CheckErrorResult { get; set; }
        public string DataRemarkState { get; set; }
        public Nullable<int> sDataSource { get; set; }
    }
}
