//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_FetchNumberFunc
    {
        public int sID { get; set; }
        public string sType { get; set; }
        public string sName { get; set; }
        public string sDescript { get; set; }
        public short sParamCount { get; set; }
        public string sParamDesc1 { get; set; }
        public byte[] sParamDesc2 { get; set; }
        public string sParamDesc3 { get; set; }
        public string sParamDesc4 { get; set; }
        public string sParamDesc5 { get; set; }
        public string sParamDesc6 { get; set; }
        public string sParamDesc7 { get; set; }
        public string sParamName1 { get; set; }
        public string sParamName2 { get; set; }
        public string sParamName3 { get; set; }
        public string sParamName4 { get; set; }
        public string sParamName5 { get; set; }
        public string sParamName6 { get; set; }
        public string sParamName7 { get; set; }
    }
}
