//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_FacilityPreserve
    {
        public int fp_id { get; set; }
        public string area_code { get; set; }
        public string unit_name { get; set; }
        public string unit_code { get; set; }
        public string fa_number { get; set; }
        public string touch_name { get; set; }
        public string touch_phone { get; set; }
        public string install_name { get; set; }
        public string install_id { get; set; }
        public Nullable<System.DateTime> install_date { get; set; }
        public string skiller { get; set; }
        public string skiller_id { get; set; }
        public string user_note { get; set; }
    }
}
