//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_ItemPreserve
    {
        public int ip_id { get; set; }
        public string unit_name { get; set; }
        public string unit_code { get; set; }
        public string ip_status { get; set; }
        public string area_code { get; set; }
        public decimal pact_money { get; set; }
        public decimal pay_money { get; set; }
        public System.DateTime pay_date { get; set; }
        public decimal pay_cash_money { get; set; }
        public decimal pra_cash_money { get; set; }
        public string duty_person { get; set; }
        public string touch_phone { get; set; }
        public string bag_file { get; set; }
        public System.DateTime pact_start { get; set; }
        public string record_name { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string user_note { get; set; }
    }
}
