//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_InternalReciveLog
    {
        public string sID { get; set; }
        public string sClassID { get; set; }
        public string sClassName { get; set; }
        public string sTBID { get; set; }
        public string sTBName { get; set; }
        public int SendYear { get; set; }
        public int SendTypeID { get; set; }
        public int SendTypeCycleID { get; set; }
        public string SendUserID { get; set; }
        public string SendUserName { get; set; }
        public string SendDWID { get; set; }
        public string SendDWName { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public string SendDescript { get; set; }
        public Nullable<int> RemarkYear { get; set; }
        public Nullable<int> RemarkTypeID { get; set; }
        public Nullable<int> RemarkTypeCycleID { get; set; }
        public string RemarkUserID { get; set; }
        public string RemarkUserName { get; set; }
        public int RemarkResultFlag { get; set; }
        public string RemarkResultDescript { get; set; }
    }
}
