//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_InternalSend
    {
        public string sID { get; set; }
        public string sClassID { get; set; }
        public string sTBID { get; set; }
        public int sYear { get; set; }
        public int sTypeID { get; set; }
        public int sTypeCycleID { get; set; }
        public string SendUserID { get; set; }
        public string SendDWID { get; set; }
        public string SendDWName { get; set; }
        public System.DateTime SendDateTime { get; set; }
        public string Descript { get; set; }
        public string ReciveUserID { get; set; }
    }
}
