//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_TBItems
    {
        public string sClassID { get; set; }
        public string sTBID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> ItemOrder { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public int Itemlen { get; set; }
        public int Itemdecimal { get; set; }
        public string CodeID { get; set; }
        public int IsMustInput { get; set; }
        public string DispFormat { get; set; }
        public Nullable<int> DispWidth { get; set; }
        public string Descript { get; set; }
    }
}
