//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_UpDataLog
    {
        public int up_id { get; set; }
        public string up_unit_id { get; set; }
        public string up_name { get; set; }
        public Nullable<System.DateTime> up_date { get; set; }
        public string up_context { get; set; }
        public Nullable<int> up_user_id { get; set; }
        public string up_user_name { get; set; }
        public Nullable<int> up_result { get; set; }
    }
}
