//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BB_ZB
    {
        public string sClassID { get; set; }
        public string sTBID { get; set; }
        public string sZBID { get; set; }
        public int sDbType { get; set; }
        public int sDispOrder { get; set; }
        public string sName { get; set; }
        public int sDataRows { get; set; }
        public int sDataCols { get; set; }
        public int sFixedRows { get; set; }
        public int sFixedCols { get; set; }
        public string sRowCheck { get; set; }
        public string sColCheck { get; set; }
        public string sCellCheck { get; set; }
        public string sTableCheck { get; set; }
        public string sCellCalc { get; set; }
        public string sGroupExpr { get; set; }
        public string sNoteInfo { get; set; }
        public string sPrintSetup { get; set; }
        public string sTotalRange { get; set; }
        public string sDataRange { get; set; }
        public string sTextRange { get; set; }
        public string SVarScript { get; set; }
        public byte[] sTemplet { get; set; }
        public string sGenernalCondition { get; set; }
        public string sReadOnlyRange { get; set; }
        public string sPersonMemoRange { get; set; }
    }
}
