//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_Define_ActorAdapter
    {
        public string RowID { get; set; }
        public string AdapterID { get; set; }
        public string AdapterName { get; set; }
        public string AdapterHandler { get; set; }
        public string UIConfig { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
