//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_Define_ProcessPublished
    {
        public string RowID { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public int ProcessVersion { get; set; }
        public string PackageID { get; set; }
        public string Content { get; set; }
        public string GraphXml { get; set; }
        public string PublisherID { get; set; }
        public string PublisherName { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public Nullable<int> IsActivity { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string ProcessIcon { get; set; }
        public string Description { get; set; }
        public string PreStartForm { get; set; }
        public string ViewForm { get; set; }
        public string VariableDefines { get; set; }
        public string SequenceID { get; set; }
        public string MessageGroups { get; set; }
    }
}
