//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_Run_WorkTaskOpinion
    {
        public string RowID { get; set; }
        public string OptinionID { get; set; }
        public string InstanceID { get; set; }
        public string TaskID { get; set; }
        public string ActivityID { get; set; }
        public string AuditOpinion { get; set; }
        public string AuditUserID { get; set; }
        public string AuditUserName { get; set; }
        public string AuditResult { get; set; }
        public string AuditResultName { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
    }
}
