//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_Run_Instance
    {
        public string RowID { get; set; }
        public string SchemeID { get; set; }
        public string InstanceID { get; set; }
        public string ProcessID { get; set; }
        public int ProcessVersion { get; set; }
        public string ProcessName { get; set; }
        public string SequenceNo { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public string BizID { get; set; }
        public string InitiatorID { get; set; }
        public string InitiatorName { get; set; }
        public string InitiatorOrgID { get; set; }
        public string InitiatorPostID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> PlanEndTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ElapsedTime { get; set; }
        public string ParentInstanceID { get; set; }
        public string ParentActivityID { get; set; }
        public string ParentTrackingID { get; set; }
        public string StateDesc { get; set; }
        public string State { get; set; }
        public string SecondState { get; set; }
        public Nullable<int> NextTokenId { get; set; }
        public int IsDeleted { get; set; }
        public Nullable<int> PlanDuration { get; set; }
    }
}
