//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_Run_Tracking
    {
        public string RowID { get; set; }
        public string InstanceID { get; set; }
        public string TrackingID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<int> ProcessVersion { get; set; }
        public Nullable<int> RecordNo { get; set; }
        public string PrevTrackingIds { get; set; }
        public string ParentTrackingID { get; set; }
        public string ActivityID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<System.DateTime> ExecutionTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Operator { get; set; }
        public string EventName { get; set; }
        public string NodeType { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> TokenId { get; set; }
        public Nullable<int> MultiTaskCount { get; set; }
    }
}
