//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_D_NewEmployees_Main
    {
        public string RowID { get; set; }
        public string BizID { get; set; }
        public string InstanceID { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string A01C01 { get; set; }
        public string A0101 { get; set; }
        public string B0001 { get; set; }
        public string B0002 { get; set; }
        public string B00022 { get; set; }
        public string B00023 { get; set; }
        public string B0003 { get; set; }
        public string A0177 { get; set; }
        public Nullable<System.DateTime> A0111 { get; set; }
        public string A0107 { get; set; }
        public Nullable<int> C0101 { get; set; }
        public string C0102 { get; set; }
        public byte[] PersonPhoto { get; set; }
    }
}
