//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPM_Run_Urged
    {
        public string RowID { get; set; }
        public string UrgedID { get; set; }
        public string InstanceID { get; set; }
        public string TaskID { get; set; }
        public Nullable<System.DateTime> UrgedTime { get; set; }
        public string UrgedUserID { get; set; }
        public string UrgedUserName { get; set; }
        public string Message { get; set; }
        public string BatchID { get; set; }
    }
}
