//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_MusterSimple
    {
        public string RowID { get; set; }
        public string MusterID { get; set; }
        public string MusterName { get; set; }
        public string MusterSortFields { get; set; }
        public string MusterModule { get; set; }
        public string MusterIsPublic { get; set; }
        public string MusterUserID { get; set; }
        public string MusterDataLimit { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
