//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Formula
    {
        public string RowID { get; set; }
        public string Module { get; set; }
        public string ModuleSection { get; set; }
        public string ModuleField { get; set; }
        public string Formula { get; set; }
        public string FormulaSql { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
