//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_LimitItems
    {
        public string RowID { get; set; }
        public string LimitID { get; set; }
        public int LimitItemOrder { get; set; }
        public string SetID { get; set; }
        public string ItemID { get; set; }
        public string CompareType { get; set; }
        public string CompareValue { get; set; }
        public string Descript { get; set; }
        public string ItemFunc { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
