//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_StatAnalysisMain
    {
        public string RowID { get; set; }
        public string StatID { get; set; }
        public string StatName { get; set; }
        public string Module { get; set; }
        public string UserID { get; set; }
        public string IsPublic { get; set; }
        public string StatKind { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
