//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class G01
    {
        public string RowID { get; set; }
        public string JobID { get; set; }
        public int DispOrder { get; set; }
        public string KeyParent { get; set; }
        public int KeyChild { get; set; }
        public string K011B { get; set; }
        public string K011C { get; set; }
        public string JobOrg { get; set; }
        public string K011G { get; set; }
        public Nullable<long> K011F { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> K0107 { get; set; }
        public Nullable<decimal> K0104 { get; set; }
        public string K011H { get; set; }
        public string K0117 { get; set; }
        public string K011I { get; set; }
        public string JobDirectLeader { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public Nullable<System.DateTime> JobEndDate { get; set; }
    }
}
