//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ExcelForm_Main
    {
        public string CatalogID { get; set; }
        public string FormID { get; set; }
        public string FormName { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string Descript { get; set; }
        public byte[] TempletExcel { get; set; }
        public string TempletHtml { get; set; }
        public string ArgFormID { get; set; }
        public string FormParentID { get; set; }
        public int FormKind { get; set; }
        public int IsAutoRowHeight { get; set; }
        public Nullable<int> FixedRows { get; set; }
        public Nullable<int> FixedCols { get; set; }
        public string ServiceVisitMode { get; set; }
        public string ServiceTimeoutUrl { get; set; }
        public string DBConnection { get; set; }
    }
}
