//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ExcelForm_DataSource
    {
        public string FormID { get; set; }
        public string SectionName { get; set; }
        public string Script { get; set; }
        public int SectionType { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public int ScriptKind { get; set; }
        public string ExcludeFields { get; set; }
    }
}
