//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ExcelForm_Input
    {
        public string FormID { get; set; }
        public string InputID { get; set; }
        public int Row { get; set; }
        public int Col { get; set; }
        public string InputName { get; set; }
        public string InputControl { get; set; }
        public string InputControlConfig { get; set; }
        public int LoadMode { get; set; }
        public string LoadConfig { get; set; }
        public int SaveMode { get; set; }
        public string SaveConfig { get; set; }
        public int SaveRefreshMode { get; set; }
        public string SaveRefreshConfig { get; set; }
        public string PrivilegeRoleName { get; set; }
        public string CheckControlConfig { get; set; }
    }
}
