//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ExcelForm_RowCol
    {
        public string FormID { get; set; }
        public int Row { get; set; }
        public int Col { get; set; }
        public string RowSectionName { get; set; }
        public string ColSectionName { get; set; }
        public string ColFieldName { get; set; }
        public string RowColConfig { get; set; }
    }
}
