//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_DataLimit
    {
        public string SID { get; set; }
        public string OwnerUser { get; set; }
        public int IsPublic { get; set; }
        public int Module { get; set; }
        public int DbType { get; set; }
        public string OperID { get; set; }
        public string SGroupName { get; set; }
        public string SName { get; set; }
        public string SMemory { get; set; }
        public Nullable<int> IsLeaderPublic { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public Nullable<int> IsSearchPublic { get; set; }
        public string Descript { get; set; }
        public string KeyWord { get; set; }
    }
}
