//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_PolicyDetail
    {
        public string GroupID { get; set; }
        public string PolicyID { get; set; }
        public string sName { get; set; }
        public string HTMLContent { get; set; }
        public string HTMLCSS { get; set; }
        public string SearchContent { get; set; }
        public System.DateTime PublicDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string FromSource { get; set; }
        public string sNameReserve { get; set; }
        public string sNameReserve2 { get; set; }
        public string sNameReserve3 { get; set; }
    }
}
