//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_CodeItems
    {
        public string CodeID { get; set; }
        public string CodeItemID { get; set; }
        public string CodeItemName { get; set; }
        public string Parent { get; set; }
        public int Child { get; set; }
        public int CodeVisible { get; set; }
        public Nullable<int> CodeOrder { get; set; }
        public string JPSign { get; set; }
    }
}
