//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_ConsoleUIGroup
    {
        public int WayID { get; set; }
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public string GroupKeyName { get; set; }
        public string ImageFile { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string GroupUrl { get; set; }
        public string GroupDescript { get; set; }
        public string DevelopID { get; set; }
        public string GroupUrlTarget { get; set; }
        public string MergeKeyID { get; set; }
        public int IsActivity { get; set; }
        public string RowID { get; set; }
    }
}
