//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_DBConnection
    {
        public string RowID { get; set; }
        public string DBID { get; set; }
        public string DBName { get; set; }
        public string DBEngineType { get; set; }
        public string CustomAssemblyName { get; set; }
        public string CustomTypeName { get; set; }
        public string ConnectionString { get; set; }
        public int IsActivity { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
