//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_LogCycleTimer
    {
        public System.DateTime SExecTime { get; set; }
        public int SElapsed { get; set; }
        public string SName { get; set; }
        public int IsSuccess { get; set; }
        public string Descript { get; set; }
    }
}
