//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Plugin
    {
        public string RowID { get; set; }
        public string PluginID { get; set; }
        public string PluginVersion { get; set; }
        public string PluginDescript { get; set; }
        public string PluginAuthor { get; set; }
        public string PluginCreateTime { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string FileMD5 { get; set; }
        public Nullable<int> IsActivity { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
