//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SchedulerPlan
    {
        public string RowID { get; set; }
        public string SchedulerID { get; set; }
        public int PlanID { get; set; }
        public string PlanName { get; set; }
        public string CronExpression { get; set; }
        public string PlanConfig { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public string Descript { get; set; }
        public Nullable<int> IsActivity { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
