//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Stamp_Unit
    {
        public string RowID { get; set; }
        public string StampID { get; set; }
        public string StampName { get; set; }
        public byte[] StampData { get; set; }
        public Nullable<long> DispOrder { get; set; }
        public string StampUnitID { get; set; }
    }
}
