//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Scheduler
    {
        public string RowID { get; set; }
        public string SchedulerID { get; set; }
        public string SchedulerName { get; set; }
        public Nullable<int> IsActivity { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Descript { get; set; }
        public string Config { get; set; }
        public Nullable<int> LastExecuteState { get; set; }
        public Nullable<System.DateTime> LastExecuteTime { get; set; }
        public Nullable<System.DateTime> NextExecuteTime { get; set; }
        public Nullable<int> ExecuteFailedTimes { get; set; }
        public Nullable<int> ExecuteSucceedTimes { get; set; }
        public string CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUserID { get; set; }
        public string LastUpdateUserName { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
