//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SystemMessage
    {
        public int MessageID { get; set; }
        public string MessageName { get; set; }
        public string MessageContent { get; set; }
        public int MessagePrior { get; set; }
        public System.DateTime SendTime { get; set; }
        public string SendUserID { get; set; }
        public string SendUserName { get; set; }
        public string SendUnitID { get; set; }
        public string SendUnitName { get; set; }
        public string ReciveUserID { get; set; }
        public string ReciveUserName { get; set; }
        public string ReciveUnitID { get; set; }
        public string ReciveUnitName { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<int> IsNotify { get; set; }
        public Nullable<System.DateTime> NotifyTime { get; set; }
        public string RelationActionName { get; set; }
        public string RelationActionUrl { get; set; }
        public string RelationActionConfig { get; set; }
    }
}
