//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SqlTemplet_Main
    {
        public string CatalogID { get; set; }
        public string TempletID { get; set; }
        public string TempletName { get; set; }
        public string TempletContent { get; set; }
        public int TempletKind { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string GenerateScriptWay { get; set; }
        public string TempletExecuteMode { get; set; }
        public string TempletReturnMode { get; set; }
        public int IsTransaction { get; set; }
        public int IsWriteLog { get; set; }
        public string EncryptConfig { get; set; }
        public string ServiceVisitMode { get; set; }
        public string ServiceTimeoutUrl { get; set; }
        public string DBConnection { get; set; }
        public int IsAnyParameter { get; set; }
    }
}
