//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_SystemModuleKeyFile
    {
        public string RowID { get; set; }
        public string sModule { get; set; }
        public string sKey { get; set; }
        public byte[] sFileData { get; set; }
        public string sFileName { get; set; }
        public string sFileExt { get; set; }
        public Nullable<int> sFileLength { get; set; }
        public string sDescript { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
