//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Todo_DataWarn
    {
        public string RowID { get; set; }
        public string WarnID { get; set; }
        public string WarnName { get; set; }
        public string WarnHintContent { get; set; }
        public string WarnHintStyle { get; set; }
        public Nullable<int> TargetKind { get; set; }
        public string TargetConfig { get; set; }
        public Nullable<int> RuleKind { get; set; }
        public string RuleConfig { get; set; }
        public Nullable<int> InterfaceKind { get; set; }
        public string InterfaceConfig { get; set; }
        public Nullable<int> TriggerCycleKind { get; set; }
        public string TriggerCycleConfig { get; set; }
        public string TriggerActionConfig { get; set; }
        public Nullable<int> IsActivity { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string WarnNumberUnit { get; set; }
    }
}
