//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Todo_Notice
    {
        public string RowID { get; set; }
        public string NoticeID { get; set; }
        public string NoticeName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Descript { get; set; }
        public byte[] AttachFile { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string TargetConfig { get; set; }
        public int IsActivity { get; set; }
        public int TargetKind { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
