//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Theme_ConfigV2
    {
        public string RowID { get; set; }
        public string ConfigID { get; set; }
        public string ConfigName { get; set; }
        public string LoginTheme { get; set; }
        public string LoginConfig { get; set; }
        public int LoginIsVerifyCode { get; set; }
        public string MainTheme { get; set; }
        public string MainColorTheme { get; set; }
        public string MainConfig { get; set; }
        public string ControlTheme { get; set; }
        public string ControlConfig { get; set; }
        public int IsDefault { get; set; }
        public int IsActivity { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
