//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_WidgetModule_Main
    {
        public string CatalogID { get; set; }
        public string ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleUrl { get; set; }
        public string ModuleInitBeforeScript { get; set; }
        public string ModuleInitAfterScript { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public int IsTemplet { get; set; }
        public string ModuleIcon { get; set; }
        public string ModuleDescript { get; set; }
        public string ModuleExtentConfig { get; set; }
        public string ModuleExtentScript { get; set; }
        public string ModuleExtendImport { get; set; }
        public int ModuleType { get; set; }
        public string ModuleInitDataConfig { get; set; }
        public string ModuleExtendIconConfig { get; set; }
        public byte[] ModuleExtendIconSvg { get; set; }
        public string EncryptConfig { get; set; }
        public int IsAnonymousExecute { get; set; }
        public string ServiceVisitMode { get; set; }
        public string ServiceTimeoutUrl { get; set; }
    }
}
