//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_WidgetModule_ToolBar
    {
        public string ModuleID { get; set; }
        public string ToolBarID { get; set; }
        public string ToolBarParentID { get; set; }
        public string ToolBarName { get; set; }
        public string ToolBarConfig { get; set; }
        public string ToolBarIcon { get; set; }
        public Nullable<int> ToolBarAlign { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public Nullable<int> ToolBarType { get; set; }
        public string ToolBarWraper { get; set; }
        public string ToolBarDataConfig { get; set; }
        public string ToolID { get; set; }
        public int IsActivity { get; set; }
        public string PropertyName { get; set; }
        public string PrivilegeFuncID { get; set; }
        public string EncryptConfig { get; set; }
    }
}
