//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_WidgetHomepage_Main
    {
        public string WidgetID { get; set; }
        public string WidgetName { get; set; }
        public int IsActivity { get; set; }
        public string PrivilegeFuncID { get; set; }
        public int DisplayMode { get; set; }
        public string WidgetScript { get; set; }
        public string WidgetTag { get; set; }
        public string WidgetIcon { get; set; }
        public Nullable<int> DispOrder { get; set; }
    }
}
