//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_WidgetModule_Files
    {
        public string CatalogID { get; set; }
        public string FileID { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string FileExt { get; set; }
        public Nullable<int> FileLength { get; set; }
        public string FileKind { get; set; }
        public string Descript { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string FileDataText { get; set; }
        public string ServiceVisitMode { get; set; }
        public string ServiceTimeoutUrl { get; set; }
    }
}
