//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_My_WidgetModule_Objects
    {
        public string ObjectKind { get; set; }
        public string CatalogID { get; set; }
        public string ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectIcon { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string ObjectExt { get; set; }
    }
}
