//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_A02
    {
        public string PersonID { get; set; }
        public string A0101 { get; set; }
        public string A0177 { get; set; }
        public Nullable<System.DateTime> A0201 { get; set; }
        public string B0001 { get; set; }
        public string B000201 { get; set; }
        public string B000202 { get; set; }
        public string B000203 { get; set; }
        public string B000204 { get; set; }
        public string B000205 { get; set; }
        public string C0104 { get; set; }
        public string E0386 { get; set; }
        public string RowID { get; set; }
        public int DispOrder { get; set; }
        public string B0001Name { get; set; }
        public string B0002Name { get; set; }
        public string B0003Name { get; set; }
        public string A0202 { get; set; }
        public string B0002 { get; set; }
        public string UnitID { get; set; }
        public string fill_check { get; set; }
        public string fill_reason { get; set; }
        public Nullable<int> fill_user_id { get; set; }
        public string A0204 { get; set; }
        public string A0203 { get; set; }
        public string if_upattend { get; set; }
    }
}
