//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_QXTJ
    {
        public string RowID { get; set; }
        public string UnitID { get; set; }
        public string B0001Name { get; set; }
        public int DispOrder { get; set; }
        public decimal B0116 { get; set; }
        public Nullable<decimal> QXTJ01 { get; set; }
        public decimal QXTJ02 { get; set; }
        public Nullable<int> People2 { get; set; }
        public Nullable<int> People { get; set; }
    }
}
