//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_JobProxy
    {
        public string SourceUserID { get; set; }
        public string SourceUserName { get; set; }
        public int SourceIsOperation { get; set; }
        public string ProxyUserID { get; set; }
        public string ProxyUserName { get; set; }
        public int ProxyIsOperation { get; set; }
        public string ProxyReason { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserID { get; set; }
    }
}
