//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_JobMain
    {
        public string OperID { get; set; }
        public string JobID { get; set; }
        public string OwnerUser { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int State { get; set; }
        public string NextStepID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> MainRowCount { get; set; }
        public string MainDescript { get; set; }
        public string NextStepUser { get; set; }
        public string UnitID { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
    }
}
