//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_JobStep
    {
        public string JobID { get; set; }
        public int JobStepID { get; set; }
        public int Parent { get; set; }
        public string OperationStepID { get; set; }
        public int State { get; set; }
        public string OwnerUser { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime ActiveTime { get; set; }
        public int IsSubmitData { get; set; }
    }
}
