//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_OperationSalaryOPSignMain
    {
        public string OPID { get; set; }
        public string CondID { get; set; }
        public string CondName { get; set; }
        public int CondType { get; set; }
        public string RelationSetID { get; set; }
        public string RelationItemID { get; set; }
        public string CodeID { get; set; }
        public string CodeItemID { get; set; }
    }
}
