//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_OperationSTData
    {
        public int STID { get; set; }
        public int STRow { get; set; }
        public int STCol { get; set; }
        public string VertID1 { get; set; }
        public string HorzID1 { get; set; }
        public string VertID2 { get; set; }
        public string HorzID2 { get; set; }
        public string VertID3 { get; set; }
        public string HorzID3 { get; set; }
        public Nullable<double> VertLimitLow1 { get; set; }
        public Nullable<double> VertLimitHigh1 { get; set; }
        public Nullable<double> VertLimitLow2 { get; set; }
        public Nullable<double> VertLimithigh2 { get; set; }
        public Nullable<double> VertLimitLow3 { get; set; }
        public Nullable<double> VertLimithigh3 { get; set; }
        public Nullable<double> HorzLimitLow1 { get; set; }
        public Nullable<double> HorzLimitHigh1 { get; set; }
        public Nullable<double> HorzLimitLow2 { get; set; }
        public Nullable<double> HorzLimithigh2 { get; set; }
        public Nullable<double> HorzLimitLow3 { get; set; }
        public Nullable<double> HorzLimithigh3 { get; set; }
        public string Result { get; set; }
    }
}
