//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_OperationSalaryOPMain
    {
        public string OperID { get; set; }
        public string OPID { get; set; }
        public int OPType { get; set; }
        public string OwnerUser { get; set; }
        public string OPName { get; set; }
        public string Options { get; set; }
        public string PrintSetup { get; set; }
        public byte[] Templet { get; set; }
        public Nullable<int> TempletRows { get; set; }
    }
}
