//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_OperationSetItemOption
    {
        public string OwnerUser { get; set; }
        public string DbWayID { get; set; }
        public string SetID { get; set; }
        public string ItemID { get; set; }
        public int IsVisible { get; set; }
        public int DispOrder { get; set; }
        public string OperID { get; set; }
    }
}
