//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_OperationMain
    {
        public int GroupID { get; set; }
        public string OperID { get; set; }
        public string SName { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string FetchScript { get; set; }
        public string SubmitScript { get; set; }
        public string FlowChartUrl { get; set; }
        public string FlowStateUrl { get; set; }
        public string LookHistoryUrl { get; set; }
        public string Descript { get; set; }
        public int RelationDbType { get; set; }
        public int TypeID { get; set; }
        public int IsActivity { get; set; }
        public string DataLimitGroup { get; set; }
        public string DataLimitScript { get; set; }
        public int IsAutoHint { get; set; }
        public Nullable<int> IsExitAskUndo { get; set; }
        public string OperIconUrl { get; set; }
        public string ArchiveWidgetModuleID { get; set; }
        public string JobStartAfterScript { get; set; }
        public int IsAutoImportData { get; set; }
        public string FetchScriptSql { get; set; }
        public string SubmitScriptSql { get; set; }
        public string DataLimitScriptSql { get; set; }
        public int IsCustomRelationDB { get; set; }
        public string ProcessingWidgetModuleID { get; set; }
        public int IsNullCantStart { get; set; }
        public string JobNumberUnit { get; set; }
        public string StartWidgetModuleID { get; set; }
    }
}
