//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WGJG02
    {
        public string RowID { get; set; }
        public string WGJG01RowID { get; set; }
        public string PersonSalaryID { get; set; }
        public string PersonID { get; set; }
        public Nullable<System.DateTime> WGJG0201 { get; set; }
        public Nullable<System.DateTime> WGJG0202 { get; set; }
        public string A0101 { get; set; }
        public string A0177 { get; set; }
        public string B0002 { get; set; }
        public string E0386 { get; set; }
        public string A0145 { get; set; }
        public string WGJG0203 { get; set; }
        public Nullable<decimal> WGJG0204 { get; set; }
        public Nullable<int> WGJG0205 { get; set; }
        public Nullable<int> WGJG0206 { get; set; }
        public Nullable<decimal> WGJG0207 { get; set; }
        public Nullable<decimal> WGJG0208 { get; set; }
        public string WGJG0209 { get; set; }
        public string WGJG0211 { get; set; }
        public Nullable<System.DateTime> WGJG0212 { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string PClassID { get; set; }
        public string UnitID { get; set; }
    }
}
