//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WGJG01_Template
    {
        public int DispOrder { get; set; }
        public string RowID { get; set; }
        public string B0001 { get; set; }
        public string B0002 { get; set; }
        public string WGJG0101 { get; set; }
        public Nullable<System.DateTime> WGJG0102 { get; set; }
        public string WGJG0103 { get; set; }
        public string WGJG0104 { get; set; }
        public string WGJG0105 { get; set; }
        public string WGJG0106 { get; set; }
        public string WGJG0203 { get; set; }
        public Nullable<int> WGJGDAY { get; set; }
        public string UnitID { get; set; }
    }
}
