//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WGJG_ZX
    {
        public string RowID { get; set; }
        public string WGJG_ZX01 { get; set; }
        public string WGJG_ZX02 { get; set; }
        public string WGJG_ZX03 { get; set; }
        public string WGJG_ZX04 { get; set; }
        public string WGJG_ZX05 { get; set; }
        public string WGJG_ZX06 { get; set; }
        public string WGJG_ZX07 { get; set; }
        public string WGJG_ZX09 { get; set; }
        public string WGJG_ZX10 { get; set; }
        public Nullable<System.DateTime> WGJG_ZX11 { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public byte[] WGJG_ZX08 { get; set; }
        public string WGJG_ZX18 { get; set; }
        public string WGJG_ZX12 { get; set; }
        public string WGJG_ZX13 { get; set; }
        public string WGJG_ZX14 { get; set; }
        public string WGJG_ZX15 { get; set; }
        public string WGJG_ZX16 { get; set; }
        public string WGJG_ZX17 { get; set; }
        public int auto_id { get; set; }
    }
}
