//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WGJG_GRZX
    {
        public string RowID { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string WGJG_GRZX01 { get; set; }
        public string WGJG_GRZX02 { get; set; }
        public string WGJG_GRZX03 { get; set; }
        public string WGJG_GRZX04 { get; set; }
        public string WGJG_GRZX05 { get; set; }
        public string WGJG_GRZX06 { get; set; }
        public string WGJG_GRZX07 { get; set; }
        public byte[] WGJG_GRZX08 { get; set; }
        public string WGJG_GRZX09 { get; set; }
        public string WGJG_GRZX10 { get; set; }
        public Nullable<System.DateTime> WGJG_GRZX11 { get; set; }
    }
}
