//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCQ2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XS_Student
    {
        public string RowID { get; set; }
        public string StudentID { get; set; }
        public string XS_Student01 { get; set; }
        public string XS_Student02 { get; set; }
        public Nullable<System.DateTime> XS_Student03 { get; set; }
        public Nullable<System.DateTime> XS_Student04 { get; set; }
        public byte[] XS_Student05 { get; set; }
        public Nullable<int> DispOrder { get; set; }
        public string XS_Student06 { get; set; }
    }
}
