
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace HCQ2_IBLL
{
	public partial interface IBLLSession
	{
	IA01BLL A01{get;set;}
		IA02BLL A02{get;set;}
		IA03BLL A03{get;set;}
		IA04BLL A04{get;set;}
		IA19BLL A19{get;set;}
		IATTACHJOBBLL ATTACHJOB{get;set;}
		IAuth_Define_DataScopeBLL Auth_Define_DataScope{get;set;}
		IAuth_Define_DataScopeItemBLL Auth_Define_DataScopeItem{get;set;}
		IAuth_Define_FuncBLL Auth_Define_Func{get;set;}
		IAuth_Define_SetDBBLL Auth_Define_SetDB{get;set;}
		IAuth_Define_SetItemBLL Auth_Define_SetItem{get;set;}
		IAuth_Define_SetTableBLL Auth_Define_SetTable{get;set;}
		IAuth_OrgRoleBLL Auth_OrgRole{get;set;}
		IAuth_PermissionBLL Auth_Permission{get;set;}
		IAuth_PermissionScopeBLL Auth_PermissionScope{get;set;}
		IAuth_RoleBLL Auth_Role{get;set;}
		IAuth_SecretLoginBLL Auth_SecretLogin{get;set;}
		IAuth_UserBLL Auth_User{get;set;}
		IAuth_UserGroupBLL Auth_UserGroup{get;set;}
		IAuth_UserGroupRoleBLL Auth_UserGroupRole{get;set;}
		IAuth_UserLogonBLL Auth_UserLogon{get;set;}
		IAuth_UserRoleBLL Auth_UserRole{get;set;}
		IAuth_UserWeixinBLL Auth_UserWeixin{get;set;}
		IB01BLL B01{get;set;}
		IBB_CashDetailBLL BB_CashDetail{get;set;}
		IBB_DWBLL BB_DW{get;set;}
		IBB_DWLevelBLL BB_DWLevel{get;set;}
		IBB_DWLevelUserBLL BB_DWLevelUser{get;set;}
		IBB_DWStateBLL BB_DWState{get;set;}
		IBB_DWStateCheckResultBLL BB_DWStateCheckResult{get;set;}
		IBB_DWTotalBLL BB_DWTotal{get;set;}
		IBB_FacilityPreserveBLL BB_FacilityPreserve{get;set;}
		IBB_FetchDataSetupBLL BB_FetchDataSetup{get;set;}
		IBB_FetchFCBLL BB_FetchFC{get;set;}
		IBB_FetchNumberFuncBLL BB_FetchNumberFunc{get;set;}
		IBB_FetchPoolLogBLL BB_FetchPoolLog{get;set;}
		IBB_InternalReciveLogBLL BB_InternalReciveLog{get;set;}
		IBB_InternalSendBLL BB_InternalSend{get;set;}
		IBB_ItemPreserveBLL BB_ItemPreserve{get;set;}
		IBB_PactDetailFlieBLL BB_PactDetailFlie{get;set;}
		IBB_ServiceUserBLL BB_ServiceUser{get;set;}
		IBB_SJ_DataSpecialBLL BB_SJ_DataSpecial{get;set;}
		IBB_SJ_NoteFloatBLL BB_SJ_NoteFloat{get;set;}
		IBB_SJ_NoteTextBLL BB_SJ_NoteText{get;set;}
		IBB_TBBLL BB_TB{get;set;}
		IBB_TBClassBLL BB_TBClass{get;set;}
		IBB_TBDataHintBLL BB_TBDataHint{get;set;}
		IBB_TBItemsBLL BB_TBItems{get;set;}
		IBB_TBRemarkUserLevelBLL BB_TBRemarkUserLevel{get;set;}
		IBB_TBRemarkUsersBLL BB_TBRemarkUsers{get;set;}
		IBB_TotalFCBLL BB_TotalFC{get;set;}
		IBB_TrackRecordBLL BB_TrackRecord{get;set;}
		IBB_TypeBLL BB_Type{get;set;}
		IBB_TypeCycleBLL BB_TypeCycle{get;set;}
		IBB_UpDataLogBLL BB_UpDataLog{get;set;}
		IBB_ZBBLL BB_ZB{get;set;}
		IBB_ZBConditionBLL BB_ZBCondition{get;set;}
		IBB_ZBVarItemsBLL BB_ZBVarItems{get;set;}
		IBMQ_DocumentBLL BMQ_Document{get;set;}
		IBPM_AgencyRuleBLL BPM_AgencyRule{get;set;}
		IBPM_AgencyRuleAssigneeBLL BPM_AgencyRuleAssignee{get;set;}
		IBPM_AgencyRuleProcessBLL BPM_AgencyRuleProcess{get;set;}
		IBPM_D_AskForLeaveDemo_MainBLL BPM_D_AskForLeaveDemo_Main{get;set;}
		IBPM_D_Leave_MainBLL BPM_D_Leave_Main{get;set;}
		IBPM_D_NewEmployees_MainBLL BPM_D_NewEmployees_Main{get;set;}
		IBPM_Define_ActionListenerBLL BPM_Define_ActionListener{get;set;}
		IBPM_Define_ActorAdapterBLL BPM_Define_ActorAdapter{get;set;}
		IBPM_Define_ActorAdapter_bakBLL BPM_Define_ActorAdapter_bak{get;set;}
		IBPM_Define_CatalogBLL BPM_Define_Catalog{get;set;}
		IBPM_Define_ConstBLL BPM_Define_Const{get;set;}
		IBPM_Define_DataModelBLL BPM_Define_DataModel{get;set;}
		IBPM_Define_FormBLL BPM_Define_Form{get;set;}
		IBPM_Define_PackageBLL BPM_Define_Package{get;set;}
		IBPM_Define_ProcessDraftBLL BPM_Define_ProcessDraft{get;set;}
		IBPM_Define_ProcessPublishedBLL BPM_Define_ProcessPublished{get;set;}
		IBPM_Define_SchemeBLL BPM_Define_Scheme{get;set;}
		IBPM_Run_InstanceBLL BPM_Run_Instance{get;set;}
		IBPM_Run_ProcessLogBLL BPM_Run_ProcessLog{get;set;}
		IBPM_Run_SchemeJobBLL BPM_Run_SchemeJob{get;set;}
		IBPM_Run_SharedTaskBLL BPM_Run_SharedTask{get;set;}
		IBPM_Run_TrackingBLL BPM_Run_Tracking{get;set;}
		IBPM_Run_UrgedBLL BPM_Run_Urged{get;set;}
		IBPM_Run_VariableBLL BPM_Run_Variable{get;set;}
		IBPM_Run_WorkTaskBLL BPM_Run_WorkTask{get;set;}
		IBPM_Run_WorkTaskOpinionBLL BPM_Run_WorkTaskOpinion{get;set;}
		IBPM_UserExtInfoBLL BPM_UserExtInfo{get;set;}
		IBPM_UsuallyOpinionBLL BPM_UsuallyOpinion{get;set;}
		ICache_BlobInfoBLL Cache_BlobInfo{get;set;}
		ICache_StatDataBLL Cache_StatData{get;set;}
		ICom_CatalogBLL Com_Catalog{get;set;}
		ICom_FormulaBLL Com_Formula{get;set;}
		ICom_JetTableItemsBLL Com_JetTableItems{get;set;}
		ICom_JetTableMainBLL Com_JetTableMain{get;set;}
		ICom_LimitItemsBLL Com_LimitItems{get;set;}
		ICom_LimitMainBLL Com_LimitMain{get;set;}
		ICom_MusterSimpleBLL Com_MusterSimple{get;set;}
		ICom_MusterSimpleFieldsBLL Com_MusterSimpleFields{get;set;}
		ICom_RelationBodyBLL Com_RelationBody{get;set;}
		ICom_RelationMainBLL Com_RelationMain{get;set;}
		ICom_SortItemsBLL Com_SortItems{get;set;}
		ICom_SortMainBLL Com_SortMain{get;set;}
		ICom_StatAnalysisItemsBLL Com_StatAnalysisItems{get;set;}
		ICom_StatAnalysisMainBLL Com_StatAnalysisMain{get;set;}
		ICom_StatLimitColumnsBLL Com_StatLimitColumns{get;set;}
		ICom_StatLimitMainBLL Com_StatLimitMain{get;set;}
		ICom_StatLimitRowsBLL Com_StatLimitRows{get;set;}
		IG01BLL G01{get;set;}
		IHR_MusterFieldsBLL HR_MusterFields{get;set;}
		IHR_MusterMainBLL HR_MusterMain{get;set;}
		IOP_ExcelForm_ArgsBLL OP_ExcelForm_Args{get;set;}
		IOP_ExcelForm_CatalogBLL OP_ExcelForm_Catalog{get;set;}
		IOP_ExcelForm_CellBLL OP_ExcelForm_Cell{get;set;}
		IOP_ExcelForm_ColBLL OP_ExcelForm_Col{get;set;}
		IOP_ExcelForm_DataSourceBLL OP_ExcelForm_DataSource{get;set;}
		IOP_ExcelForm_DataSourceParseBLL OP_ExcelForm_DataSourceParse{get;set;}
		IOP_ExcelForm_InputBLL OP_ExcelForm_Input{get;set;}
		IOP_ExcelForm_InputTableBLL OP_ExcelForm_InputTable{get;set;}
		IOP_ExcelForm_InputTableFieldBLL OP_ExcelForm_InputTableField{get;set;}
		IOP_ExcelForm_MainBLL OP_ExcelForm_Main{get;set;}
		IOP_ExcelForm_PrivilegeBLL OP_ExcelForm_Privilege{get;set;}
		IOP_ExcelForm_RowBLL OP_ExcelForm_Row{get;set;}
		IOP_ExcelForm_RowColBLL OP_ExcelForm_RowCol{get;set;}
		IProject_LogApiBLL Project_LogApi{get;set;}
		IRC_DataHintBLL RC_DataHint{get;set;}
		IRC_DataHintStateBLL RC_DataHintState{get;set;}
		IRC_DataLimitBLL RC_DataLimit{get;set;}
		IRC_ImportClientDataWayBLL RC_ImportClientDataWay{get;set;}
		IRC_InfoScriptBLL RC_InfoScript{get;set;}
		IRC_InfoScriptOrderBLL RC_InfoScriptOrder{get;set;}
		IRC_JTMainBLL RC_JTMain{get;set;}
		IRC_MusterMainBLL RC_MusterMain{get;set;}
		IRC_PolicyAttachBLL RC_PolicyAttach{get;set;}
		IRC_PolicyDetailBLL RC_PolicyDetail{get;set;}
		IRC_PolicyGroupBLL RC_PolicyGroup{get;set;}
		IRC_SearchContainerResultBLL RC_SearchContainerResult{get;set;}
		IRC_StatMainBLL RC_StatMain{get;set;}
		IRC_StatMusterFieldBLL RC_StatMusterField{get;set;}
		ISM_CodeItemsBLL SM_CodeItems{get;set;}
		ISM_CodeTableBLL SM_CodeTable{get;set;}
		ISM_CodeTableGroupBLL SM_CodeTableGroup{get;set;}
		ISM_ConsoleUIGroupBLL SM_ConsoleUIGroup{get;set;}
		ISM_ConsoleUIItemBLL SM_ConsoleUIItem{get;set;}
		ISM_ConsoleUIWayBLL SM_ConsoleUIWay{get;set;}
		ISM_ConsoleUIWayRoleBLL SM_ConsoleUIWayRole{get;set;}
		ISM_DBConnectionBLL SM_DBConnection{get;set;}
		ISM_GlobalScriptBLL SM_GlobalScript{get;set;}
		ISM_IdentityBLL SM_Identity{get;set;}
		ISM_LogBLL SM_Log{get;set;}
		ISM_LogCycleTimerBLL SM_LogCycleTimer{get;set;}
		ISM_LogDevelopBLL SM_LogDevelop{get;set;}
		ISM_LogSystemBLL SM_LogSystem{get;set;}
		ISM_PersonClassBLL SM_PersonClass{get;set;}
		ISM_PluginBLL SM_Plugin{get;set;}
		ISM_Prototype_SimpleBLL SM_Prototype_Simple{get;set;}
		ISM_PYBLL SM_PY{get;set;}
		ISM_SchedulerBLL SM_Scheduler{get;set;}
		ISM_SchedulerNotifyBLL SM_SchedulerNotify{get;set;}
		ISM_SchedulerPlanBLL SM_SchedulerPlan{get;set;}
		ISM_SchedulerRunLogBLL SM_SchedulerRunLog{get;set;}
		ISM_SchedulerTaskBLL SM_SchedulerTask{get;set;}
		ISM_SequenceManageBLL SM_SequenceManage{get;set;}
		ISM_SetDBBLL SM_SetDB{get;set;}
		ISM_SetItemCalcBLL SM_SetItemCalc{get;set;}
		ISM_SetItemsBLL SM_SetItems{get;set;}
		ISM_SetItemUserConfigBLL SM_SetItemUserConfig{get;set;}
		ISM_SetTableBLL SM_SetTable{get;set;}
		ISM_SetTableUserConfigBLL SM_SetTableUserConfig{get;set;}
		ISM_SetWayUserConfigBLL SM_SetWayUserConfig{get;set;}
		ISM_SqlTemplet_ArgsBLL SM_SqlTemplet_Args{get;set;}
		ISM_SqlTemplet_CatalogBLL SM_SqlTemplet_Catalog{get;set;}
		ISM_SqlTemplet_MainBLL SM_SqlTemplet_Main{get;set;}
		ISM_Stamp_UnitBLL SM_Stamp_Unit{get;set;}
		ISM_Stamp_UnitUserBLL SM_Stamp_UnitUser{get;set;}
		ISM_SystemKeyValueBLL SM_SystemKeyValue{get;set;}
		ISM_SystemMessageBLL SM_SystemMessage{get;set;}
		ISM_SystemModuleKeyFileBLL SM_SystemModuleKeyFile{get;set;}
		ISM_SystemModuleKeyValueBLL SM_SystemModuleKeyValue{get;set;}
		ISM_Theme_ConfigV2BLL SM_Theme_ConfigV2{get;set;}
		ISM_Theme_ConfigV2_FileBLL SM_Theme_ConfigV2_File{get;set;}
		ISM_Theme_ConfigV2_RoleBLL SM_Theme_ConfigV2_Role{get;set;}
		ISM_Todo_DataWarnBLL SM_Todo_DataWarn{get;set;}
		ISM_Todo_NoticeBLL SM_Todo_Notice{get;set;}
		ISM_UserKeyValueBLL SM_UserKeyValue{get;set;}
		ISM_UserKeyValueExBLL SM_UserKeyValueEx{get;set;}
		ISM_UserOnlineLoggerBLL SM_UserOnlineLogger{get;set;}
		ISM_UserRelationBLL SM_UserRelation{get;set;}
		ISM_UserRelationItemBLL SM_UserRelationItem{get;set;}
		ISM_VersionBLL SM_Version{get;set;}
		ISM_Weixin_SystemConfigBLL SM_Weixin_SystemConfig{get;set;}
		ISM_WidgetHomepage_MainBLL SM_WidgetHomepage_Main{get;set;}
		ISM_WidgetHomepage_UserConfigBLL SM_WidgetHomepage_UserConfig{get;set;}
		ISM_WidgetModule_ArgsBLL SM_WidgetModule_Args{get;set;}
		ISM_WidgetModule_CatalogBLL SM_WidgetModule_Catalog{get;set;}
		ISM_WidgetModule_FilesBLL SM_WidgetModule_Files{get;set;}
		ISM_WidgetModule_MainBLL SM_WidgetModule_Main{get;set;}
		ISM_WidgetModule_ObjectConfigBLL SM_WidgetModule_ObjectConfig{get;set;}
		ISM_WidgetModule_ToolBLL SM_WidgetModule_Tool{get;set;}
		ISM_WidgetModule_ToolBarBLL SM_WidgetModule_ToolBar{get;set;}
		IsysdiagramsBLL sysdiagrams{get;set;}
		IT_AreaInfoBLL T_AreaInfo{get;set;}
		IT_AreaPermissRelationBLL T_AreaPermissRelation{get;set;}
		IT_AskManagerBLL T_AskManager{get;set;}
		IT_B01PermissRelationBLL T_B01PermissRelation{get;set;}
		IT_ComplaintsBLL T_Complaints{get;set;}
		IT_CompProInfoBLL T_CompProInfo{get;set;}
		IT_DocFolderPermissRelationBLL T_DocFolderPermissRelation{get;set;}
		IT_DocumentFolderBLL T_DocumentFolder{get;set;}
		IT_DocumentFolderRelationBLL T_DocumentFolderRelation{get;set;}
		IT_DocumentInfoBLL T_DocumentInfo{get;set;}
		IT_DocumentSetTypeBLL T_DocumentSetType{get;set;}
		IT_ElementPermissRelationBLL T_ElementPermissRelation{get;set;}
		IT_EnterDetailBLL T_EnterDetail{get;set;}
		IT_EquipmentBLL T_Equipment{get;set;}
		IT_ExceptionLogBLL T_ExceptionLog{get;set;}
		IT_FilePermissRelationBLL T_FilePermissRelation{get;set;}
		IT_FolderPermissRelationBLL T_FolderPermissRelation{get;set;}
		IT_FunctionBLL T_Function{get;set;}
		IT_ImplementBLL T_Implement{get;set;}
		IT_ItemCodeBLL T_ItemCode{get;set;}
		IT_ItemCodeMenumBLL T_ItemCodeMenum{get;set;}
		IT_JobResumeRelationBLL T_JobResumeRelation{get;set;}
		IT_LimitUserBLL T_LimitUser{get;set;}
		IT_LoginBLL T_Login{get;set;}
		IT_LogSetingBLL T_LogSeting{get;set;}
		IT_LogSetingDetailBLL T_LogSetingDetail{get;set;}
		IT_MessageNoticeBLL T_MessageNotice{get;set;}
		IT_ModulePermissRelationBLL T_ModulePermissRelation{get;set;}
		IT_Org_UserBLL T_Org_User{get;set;}
		IT_OrgFolderBLL T_OrgFolder{get;set;}
		IT_OrgUserRelationBLL T_OrgUserRelation{get;set;}
		IT_PageElementBLL T_PageElement{get;set;}
		IT_PageFileBLL T_PageFile{get;set;}
		IT_PageFolderBLL T_PageFolder{get;set;}
		IT_PayAccountBLL T_PayAccount{get;set;}
		IT_PerFuncRelationBLL T_PerFuncRelation{get;set;}
		IT_PermissConfigBLL T_PermissConfig{get;set;}
		IT_PermissionsBLL T_Permissions{get;set;}
		IT_RoleBLL T_Role{get;set;}
		IT_RoleGroupRelationBLL T_RoleGroupRelation{get;set;}
		IT_RolePermissRelationBLL T_RolePermissRelation{get;set;}
		IT_SetMainPageBLL T_SetMainPage{get;set;}
		IT_SynchronousBLL T_Synchronous{get;set;}
		IT_SysModuleBLL T_SysModule{get;set;}
		IT_TableBLL T_Table{get;set;}
		IT_TableFieldBLL T_TableField{get;set;}
		IT_TodoListBLL T_TodoList{get;set;}
		IT_UserBLL T_User{get;set;}
		IT_UserGroupBLL T_UserGroup{get;set;}
		IT_UserGroupRelationBLL T_UserGroupRelation{get;set;}
		IT_UserRoleRelationBLL T_UserRoleRelation{get;set;}
		IT_UserUnitRelationBLL T_UserUnitRelation{get;set;}
		IT_UseWorkerBLL T_UseWorker{get;set;}
		IV_Auth_Per_00001_System_BPM_StartBLL V_Auth_Per_00001_System_BPM_Start{get;set;}
		IV_Auth_Per_00001_System_Operation_StartBLL V_Auth_Per_00001_System_Operation_Start{get;set;}
		IV_Auth_Per_00001_System_Org_TreeBLL V_Auth_Per_00001_System_Org_Tree{get;set;}
		IV_Auth_Per_00001_System_Person_ReadwriteBLL V_Auth_Per_00001_System_Person_Readwrite{get;set;}
		IV_Auth_Per_00001_System_PersonClassBLL V_Auth_Per_00001_System_PersonClass{get;set;}
		IV_Auth_Per_00002_System_BPM_StartBLL V_Auth_Per_00002_System_BPM_Start{get;set;}
		IV_Auth_Per_00002_System_Operation_StartBLL V_Auth_Per_00002_System_Operation_Start{get;set;}
		IV_Auth_Per_00002_System_Org_TreeBLL V_Auth_Per_00002_System_Org_Tree{get;set;}
		IV_Auth_Per_00002_System_Person_ReadwriteBLL V_Auth_Per_00002_System_Person_Readwrite{get;set;}
		IV_Auth_Per_00002_System_PersonClassBLL V_Auth_Per_00002_System_PersonClass{get;set;}
		IV_Auth_Per_anonymous_System_BPM_StartBLL V_Auth_Per_anonymous_System_BPM_Start{get;set;}
		IV_Auth_Per_anonymous_System_Operation_StartBLL V_Auth_Per_anonymous_System_Operation_Start{get;set;}
		IV_Auth_Per_anonymous_System_Org_TreeBLL V_Auth_Per_anonymous_System_Org_Tree{get;set;}
		IV_Auth_Per_anonymous_System_Person_ReadwriteBLL V_Auth_Per_anonymous_System_Person_Readwrite{get;set;}
		IV_Auth_Per_anonymous_System_PersonClassBLL V_Auth_Per_anonymous_System_PersonClass{get;set;}
		IV_Auth_Per_U00000B_System_BPM_StartBLL V_Auth_Per_U00000B_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000B_System_Operation_StartBLL V_Auth_Per_U00000B_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000B_System_Org_TreeBLL V_Auth_Per_U00000B_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000B_System_Person_ReadwriteBLL V_Auth_Per_U00000B_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000B_System_PersonClassBLL V_Auth_Per_U00000B_System_PersonClass{get;set;}
		IV_Auth_Per_U00000C_System_BPM_StartBLL V_Auth_Per_U00000C_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000C_System_Operation_StartBLL V_Auth_Per_U00000C_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000C_System_Org_TreeBLL V_Auth_Per_U00000C_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000C_System_Person_ReadwriteBLL V_Auth_Per_U00000C_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000C_System_PersonClassBLL V_Auth_Per_U00000C_System_PersonClass{get;set;}
		IV_Auth_Per_U00000D_System_BPM_StartBLL V_Auth_Per_U00000D_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000D_System_Operation_StartBLL V_Auth_Per_U00000D_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000D_System_Org_TreeBLL V_Auth_Per_U00000D_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000D_System_Person_ReadwriteBLL V_Auth_Per_U00000D_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000D_System_PersonClassBLL V_Auth_Per_U00000D_System_PersonClass{get;set;}
		IV_Auth_Per_U00000E_System_BPM_StartBLL V_Auth_Per_U00000E_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000E_System_Operation_StartBLL V_Auth_Per_U00000E_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000E_System_Org_TreeBLL V_Auth_Per_U00000E_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000E_System_Person_ReadwriteBLL V_Auth_Per_U00000E_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000E_System_PersonClassBLL V_Auth_Per_U00000E_System_PersonClass{get;set;}
		IV_Auth_Per_U00000F_System_BPM_StartBLL V_Auth_Per_U00000F_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000F_System_Operation_StartBLL V_Auth_Per_U00000F_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000F_System_Org_TreeBLL V_Auth_Per_U00000F_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000F_System_Person_ReadwriteBLL V_Auth_Per_U00000F_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000F_System_PersonClassBLL V_Auth_Per_U00000F_System_PersonClass{get;set;}
		IV_Auth_Per_U00000G_System_BPM_StartBLL V_Auth_Per_U00000G_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000G_System_Operation_StartBLL V_Auth_Per_U00000G_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000G_System_Org_TreeBLL V_Auth_Per_U00000G_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000G_System_Person_ReadwriteBLL V_Auth_Per_U00000G_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000G_System_PersonClassBLL V_Auth_Per_U00000G_System_PersonClass{get;set;}
		IV_Auth_Per_U00000I_System_BPM_StartBLL V_Auth_Per_U00000I_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000I_System_Operation_StartBLL V_Auth_Per_U00000I_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000I_System_Org_TreeBLL V_Auth_Per_U00000I_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000I_System_Person_ReadwriteBLL V_Auth_Per_U00000I_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000I_System_PersonClassBLL V_Auth_Per_U00000I_System_PersonClass{get;set;}
		IV_Auth_Per_U00000J_System_BPM_StartBLL V_Auth_Per_U00000J_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000J_System_Operation_StartBLL V_Auth_Per_U00000J_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000J_System_Org_TreeBLL V_Auth_Per_U00000J_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000J_System_Person_ReadwriteBLL V_Auth_Per_U00000J_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000J_System_PersonClassBLL V_Auth_Per_U00000J_System_PersonClass{get;set;}
		IV_Auth_Per_U00000K_System_BPM_StartBLL V_Auth_Per_U00000K_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000K_System_Operation_StartBLL V_Auth_Per_U00000K_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000K_System_Org_TreeBLL V_Auth_Per_U00000K_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000K_System_Person_ReadwriteBLL V_Auth_Per_U00000K_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000K_System_PersonClassBLL V_Auth_Per_U00000K_System_PersonClass{get;set;}
		IV_Auth_Per_U00000L_System_BPM_StartBLL V_Auth_Per_U00000L_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000L_System_Operation_StartBLL V_Auth_Per_U00000L_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000L_System_Org_TreeBLL V_Auth_Per_U00000L_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000L_System_Person_ReadwriteBLL V_Auth_Per_U00000L_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000L_System_PersonClassBLL V_Auth_Per_U00000L_System_PersonClass{get;set;}
		IV_Auth_Per_U00000M_System_BPM_StartBLL V_Auth_Per_U00000M_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000M_System_Operation_StartBLL V_Auth_Per_U00000M_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000M_System_Org_TreeBLL V_Auth_Per_U00000M_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000M_System_Person_ReadwriteBLL V_Auth_Per_U00000M_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000M_System_PersonClassBLL V_Auth_Per_U00000M_System_PersonClass{get;set;}
		IV_Auth_Per_U00000O_System_BPM_StartBLL V_Auth_Per_U00000O_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000O_System_Operation_StartBLL V_Auth_Per_U00000O_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000O_System_Org_TreeBLL V_Auth_Per_U00000O_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000O_System_Person_ReadwriteBLL V_Auth_Per_U00000O_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000O_System_PersonClassBLL V_Auth_Per_U00000O_System_PersonClass{get;set;}
		IV_Auth_Per_U00000P_System_BPM_StartBLL V_Auth_Per_U00000P_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000P_System_Operation_StartBLL V_Auth_Per_U00000P_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000P_System_Org_TreeBLL V_Auth_Per_U00000P_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000P_System_Person_ReadwriteBLL V_Auth_Per_U00000P_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000P_System_PersonClassBLL V_Auth_Per_U00000P_System_PersonClass{get;set;}
		IV_Auth_Per_U00000R_System_BPM_StartBLL V_Auth_Per_U00000R_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000R_System_Operation_StartBLL V_Auth_Per_U00000R_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000R_System_Org_TreeBLL V_Auth_Per_U00000R_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000R_System_Person_ReadwriteBLL V_Auth_Per_U00000R_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000R_System_PersonClassBLL V_Auth_Per_U00000R_System_PersonClass{get;set;}
		IV_Auth_Per_U00000S_System_BPM_StartBLL V_Auth_Per_U00000S_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000S_System_Operation_StartBLL V_Auth_Per_U00000S_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000S_System_Org_TreeBLL V_Auth_Per_U00000S_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000S_System_Person_ReadwriteBLL V_Auth_Per_U00000S_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000S_System_PersonClassBLL V_Auth_Per_U00000S_System_PersonClass{get;set;}
		IV_Auth_Per_U00000T_System_BPM_StartBLL V_Auth_Per_U00000T_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000T_System_Operation_StartBLL V_Auth_Per_U00000T_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000T_System_Org_TreeBLL V_Auth_Per_U00000T_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000T_System_Person_ReadwriteBLL V_Auth_Per_U00000T_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000T_System_PersonClassBLL V_Auth_Per_U00000T_System_PersonClass{get;set;}
		IV_Auth_Per_U00000U_System_BPM_StartBLL V_Auth_Per_U00000U_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000U_System_Operation_StartBLL V_Auth_Per_U00000U_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000U_System_Org_TreeBLL V_Auth_Per_U00000U_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000U_System_Person_ReadwriteBLL V_Auth_Per_U00000U_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000U_System_PersonClassBLL V_Auth_Per_U00000U_System_PersonClass{get;set;}
		IV_Auth_Per_U00000V_System_BPM_StartBLL V_Auth_Per_U00000V_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000V_System_Operation_StartBLL V_Auth_Per_U00000V_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000V_System_Org_TreeBLL V_Auth_Per_U00000V_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000V_System_Person_ReadwriteBLL V_Auth_Per_U00000V_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000V_System_PersonClassBLL V_Auth_Per_U00000V_System_PersonClass{get;set;}
		IV_Auth_Per_U00000X_System_BPM_StartBLL V_Auth_Per_U00000X_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000X_System_Operation_StartBLL V_Auth_Per_U00000X_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000X_System_Org_TreeBLL V_Auth_Per_U00000X_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000X_System_Person_ReadwriteBLL V_Auth_Per_U00000X_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000X_System_PersonClassBLL V_Auth_Per_U00000X_System_PersonClass{get;set;}
		IV_Auth_Per_U00000Y_System_BPM_StartBLL V_Auth_Per_U00000Y_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000Y_System_Operation_StartBLL V_Auth_Per_U00000Y_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000Y_System_Org_TreeBLL V_Auth_Per_U00000Y_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000Y_System_Person_ReadwriteBLL V_Auth_Per_U00000Y_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000Y_System_PersonClassBLL V_Auth_Per_U00000Y_System_PersonClass{get;set;}
		IV_Auth_Per_U00000Z_System_BPM_StartBLL V_Auth_Per_U00000Z_System_BPM_Start{get;set;}
		IV_Auth_Per_U00000Z_System_Operation_StartBLL V_Auth_Per_U00000Z_System_Operation_Start{get;set;}
		IV_Auth_Per_U00000Z_System_Org_TreeBLL V_Auth_Per_U00000Z_System_Org_Tree{get;set;}
		IV_Auth_Per_U00000Z_System_Person_ReadwriteBLL V_Auth_Per_U00000Z_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U00000Z_System_PersonClassBLL V_Auth_Per_U00000Z_System_PersonClass{get;set;}
		IV_Auth_Per_U000010_System_BPM_StartBLL V_Auth_Per_U000010_System_BPM_Start{get;set;}
		IV_Auth_Per_U000010_System_Operation_StartBLL V_Auth_Per_U000010_System_Operation_Start{get;set;}
		IV_Auth_Per_U000010_System_Org_TreeBLL V_Auth_Per_U000010_System_Org_Tree{get;set;}
		IV_Auth_Per_U000010_System_Person_ReadwriteBLL V_Auth_Per_U000010_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U000010_System_PersonClassBLL V_Auth_Per_U000010_System_PersonClass{get;set;}
		IV_Auth_Per_U000011_System_BPM_StartBLL V_Auth_Per_U000011_System_BPM_Start{get;set;}
		IV_Auth_Per_U000011_System_Operation_StartBLL V_Auth_Per_U000011_System_Operation_Start{get;set;}
		IV_Auth_Per_U000011_System_Org_TreeBLL V_Auth_Per_U000011_System_Org_Tree{get;set;}
		IV_Auth_Per_U000011_System_Person_ReadwriteBLL V_Auth_Per_U000011_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U000011_System_PersonClassBLL V_Auth_Per_U000011_System_PersonClass{get;set;}
		IV_Auth_Per_U000012_System_BPM_StartBLL V_Auth_Per_U000012_System_BPM_Start{get;set;}
		IV_Auth_Per_U000012_System_Operation_StartBLL V_Auth_Per_U000012_System_Operation_Start{get;set;}
		IV_Auth_Per_U000012_System_Org_TreeBLL V_Auth_Per_U000012_System_Org_Tree{get;set;}
		IV_Auth_Per_U000012_System_Person_ReadwriteBLL V_Auth_Per_U000012_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U000012_System_PersonClassBLL V_Auth_Per_U000012_System_PersonClass{get;set;}
		IV_Auth_Per_U000014_System_BPM_StartBLL V_Auth_Per_U000014_System_BPM_Start{get;set;}
		IV_Auth_Per_U000014_System_Operation_StartBLL V_Auth_Per_U000014_System_Operation_Start{get;set;}
		IV_Auth_Per_U000014_System_Org_TreeBLL V_Auth_Per_U000014_System_Org_Tree{get;set;}
		IV_Auth_Per_U000014_System_Person_ReadwriteBLL V_Auth_Per_U000014_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U000014_System_PersonClassBLL V_Auth_Per_U000014_System_PersonClass{get;set;}
		IV_Auth_Per_U000015_System_BPM_StartBLL V_Auth_Per_U000015_System_BPM_Start{get;set;}
		IV_Auth_Per_U000015_System_Operation_StartBLL V_Auth_Per_U000015_System_Operation_Start{get;set;}
		IV_Auth_Per_U000015_System_Org_TreeBLL V_Auth_Per_U000015_System_Org_Tree{get;set;}
		IV_Auth_Per_U000015_System_Person_ReadwriteBLL V_Auth_Per_U000015_System_Person_Readwrite{get;set;}
		IV_Auth_Per_U000015_System_PersonClassBLL V_Auth_Per_U000015_System_PersonClass{get;set;}
		IV_My_WidgetModule_ObjectsBLL V_My_WidgetModule_Objects{get;set;}
		IView_A02BLL View_A02{get;set;}
		IView_Auth_UserBLL View_Auth_User{get;set;}
		IView_CatalogDocumentBLL View_CatalogDocument{get;set;}
		IView_Com_JetTableItemsBLL View_Com_JetTableItems{get;set;}
		IView_QXTJBLL View_QXTJ{get;set;}
		IWF_JobMainBLL WF_JobMain{get;set;}
		IWF_JobMainExcludeChooseBLL WF_JobMainExcludeChoose{get;set;}
		IWF_JobOpinionBLL WF_JobOpinion{get;set;}
		IWF_JobProxyBLL WF_JobProxy{get;set;}
		IWF_JobSaveOrgBLL WF_JobSaveOrg{get;set;}
		IWF_JobStepBLL WF_JobStep{get;set;}
		IWF_OperationCalcBLL WF_OperationCalc{get;set;}
		IWF_OperationDocumentBLL WF_OperationDocument{get;set;}
		IWF_OperationGroupBLL WF_OperationGroup{get;set;}
		IWF_OperationKeyValueBLL WF_OperationKeyValue{get;set;}
		IWF_OperationMainBLL WF_OperationMain{get;set;}
		IWF_OperationOutPutBLL WF_OperationOutPut{get;set;}
		IWF_OperationSalaryOPItemBLL WF_OperationSalaryOPItem{get;set;}
		IWF_OperationSalaryOPMainBLL WF_OperationSalaryOPMain{get;set;}
		IWF_OperationSalaryOPSignItemBLL WF_OperationSalaryOPSignItem{get;set;}
		IWF_OperationSalaryOPSignMainBLL WF_OperationSalaryOPSignMain{get;set;}
		IWF_OperationSetItemOptionBLL WF_OperationSetItemOption{get;set;}
		IWF_OperationSetItemsBLL WF_OperationSetItems{get;set;}
		IWF_OperationSetTableBLL WF_OperationSetTable{get;set;}
		IWF_OperationSetTableOptionBLL WF_OperationSetTableOption{get;set;}
		IWF_OperationSTCodeItemsBLL WF_OperationSTCodeItems{get;set;}
		IWF_OperationSTDataBLL WF_OperationSTData{get;set;}
		IWF_OperationStepBLL WF_OperationStep{get;set;}
		IWF_OperationStepPrivilegeBLL WF_OperationStepPrivilege{get;set;}
		IWF_OperationSTMainBLL WF_OperationSTMain{get;set;}
		IWF_OperationSTSetItemsBLL WF_OperationSTSetItems{get;set;}
		IWF_OperationTypeBLL WF_OperationType{get;set;}
		IWGJG_GRZXBLL WGJG_GRZX{get;set;}
		IWGJG_WarnDataBLL WGJG_WarnData{get;set;}
		IWGJG_ZXBLL WGJG_ZX{get;set;}
		IWGJG01BLL WGJG01{get;set;}
		IWGJG01_TemplateBLL WGJG01_Template{get;set;}
		IWGJG02BLL WGJG02{get;set;}
		IWGJG02_TemplateBLL WGJG02_Template{get;set;}
		IXS_StudentBLL XS_Student{get;set;}
		IXS_StudentScoreBLL XS_StudentScore{get;set;}
		}
}